### PR TITLE
Fix: Ignore first config changes notification on start-up

### PR DESCRIPTION
**Pull request by lenny-intel**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

First notification of config changes on start-up doesn't contain any changes, but causes issues with overrides that were just applied.

Issue Number: #72

## What is the new behavior?

First notification of config changes on start-up are now skipped

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

### CODE REVIEW

**Comment by brandonforster** [comment]
Can you provide some detailed verification steps? I'm having trouble following along with what exactly this is doing.

**Comment by lenny-intel** [comment]
@brandonforster do the following to see the issue that this fixes:

1. Stop edgex stack if running  & Prune docker the volumes
2. Pull latest images
3. Start up the EdgeX stack (i.e. mongo-no-sect)
4. Verify data is flowing from device virtual by view logs for Core Data.
5. View logs for `app-service-configurable-rules` and see events are not being logged with level INFO
6. Edit compose file and add `Writable_LogLevel: DEBUG` to `app-service-configurable-rules` environment section
7. Restart `app-service-configurable-rules`
8. View logs for `app-service-configurable-rules` and see events are `STILL` not being logged since level is still INFO, but you do see override logged
```
'Writable.LogLevel' by environment variable: Writable_LogLevel=DEBUG"
```

Verifying the fix requires updating the SDK with this bootstrap and then updating app-service-configurable which I have done locally and verified.

**Comment by brandonforster** [comment]
`Verifying the fix requires updating the SDK with this bootstrap and then updating app-service-configurable which I have done locally and verified.`

You've lost me. I tried running the `docker-compose-nexus-mongo-no-secty` compose file, but stopped when I realized I was going to be pulling the nightly image, not something that would incorporate these changes. I also don't see how I am supposed to use the SDK and see the changes running.

Can you please provide more explicit verification steps?

**Comment by lenny-intel** [comment]
> Can you please provide more explicit verification steps?

1. Update the app-functions-sdk-go's go.mod to use local go-mod-bootstrap (my branch)
```
replace github.com/edgexfoundry/go-mod-bootstrap => ../go-mod-bootstrap
```
2. Update app-service-configurable's go mode to use your local app-functions-sdk-go and local go-mod-bootstrap (my branch)
```
replace github.com/edgexfoundry/app-functions-sdk-go => ../app-functions-sdk-go

replace github.com/edgexfoundry/go-mod-bootstrap => ../go-mod-bootstrap

```
3. Build app-service-configurable
4. Run edgex stack as described earlier
5. Run app-service-configurable native with `-cp -p=sample` options (this will push config into consul)
```
./app-service-configurable -cp -p=sample
```
6. Verify no DEBUG messages in log
7. Stop your app-service-configurable
8. Set environment variable Writable_LogLevel=DEBUG
9. Rerun app-service-configurable as before
```
Writable_LogLevel=DEBUG ./app-service-configurable -cp -p=sample
```
10. Verify log contains debug messages

**Pull request merged**
