### PR TITLE
[WIP] EdgeX DevOps: New build automation for go-mod-bootstrap

### PR DESCRIPTION
**Pull request by vishwassp-hcl-intel**
Signed-off-by: Vishwas SP <vishwasx.s.premachandra@intel.com>

### CODE REVIEW

**Comment by vishwassp-hcl-intel** [comment]
> See comment on PR.

Thanks @michaelestrin .. There are some dependent changes are being prepared. I shall update the PR by removing [WIP] for the review once it is ready.

**Comment by michaelestrin** [comment]
> I shall update the PR by removing [WIP] for the review once it is ready.

When you're ready for me to review it again, just hit the re-review button (circle with arrows):

image


@vishwassp-hcl-intel

**Comment by ernestojeda** [comment]
@michaelestrin I am closing this PR. I have the latest code on my fork and will open the PR.

**Comment by vishwassp-hcl-intel** [comment]
@ernestojeda is creating a new one

**Pull request closed without merging**
