### PR TITLE
Feature/fix issue 2200

### PR DESCRIPTION
**Pull request by tingyuz**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?
go-mod-boostrap only exposes interface of retrieving database credentials. 

Issue Number:
https://github.com/edgexfoundry/edgex-go/issues/2200

## What is the new behavior?
Adding new interface to expose a method of retrieving SSL cert key pair.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Are there any specific instructions or things that should be known prior to reviewing?
The new interface CertificateProvider and the method of GetCertificateKeyPair() will be helpful for security-proxy-setup as well as other core microservices in the future.
1. The security-proxy-setup already adopted go-mod-bootstrap module. The new interface will not break its existing behaviors.
2. When the environment variable EDGEX_SECURITY_SECRET_STORE is set up as false which means security for EdgeX is off, the user will use a docker-compose file that doesn't include any security component.
3. There is a plan to add certificate key pair for core microservices ( such as data, metadata, commend etc.) to enable Https in the future. This interface and method can be used for such security enhancement in the future. 

## Other information

### CODE REVIEW

**Comment by bnevis-i** [comment]
See https://github.com/edgexfoundry/edgex-go/issues/2200

**Comment by bnevis-i** [comment]
- This PR has multiple commits and should be reduced to a single commit.
- Commit description should follow conventional commits naming style.
- No unit test for the newly added code
- Not sure if need to abbreviate Certificate to Cert and PrivateKey to Key...

Otherwise straightforward and LGTM with the general approach.  Did not realize that bootstrap did not provide a way to get to the secretstoreclient directly.

**Comment by michaelestrin** [comment]
> Did not realize that bootstrap did not provide a way to get to the secretstoreclient directly.

By design.  It's an implementation detail.  The secrets bootstrap was intended to encapsulate the idea of getting secrets -- whether via secretstoreclient, from configuration, or from some other method.  

I haven't reviewed this PR and would discourage leaking secretstoreclient (or any other implementation details) outside of the secret bootstrap implementation.

FWIW.  ;)

**Comment by bnevis-i** [comment]
Are third party application vendors expected to use go-mod-bootstrap?  If so, we should be thinking about a way for them to obtain application-specific secrets that doesn't involve forking go-mod-bootstrap to add a custom provider for their particular application.

**Comment by michaelestrin** [comment]
> Are third party application vendors expected to use go-mod-bootstrap?

I can't speak to that.  As far as I know, only go-mod-core-contracts is intended to be an externally consumable module.  

If someone wants to have a custom module, they simply provide a custom bootstrap handler implementation.

**Comment by lenny-intel** [comment]
> Are third party application vendors expected to use go-mod-bootstrap? If so, we should be thinking about a way for them to obtain application-specific secrets that doesn't involve forking go-mod-bootstrap to add a custom provider for their particular application.

@bnevis-i No they are not expected to use it directly. They will use it indirectly via the App and Device SDKs, which each will have the custom provider.

**Comment by tingyuz** [comment]
> * This PR has multiple commits and should be reduced to a single commit.
> * Commit description should follow conventional commits naming style.
> * No unit test for the newly added code
> * Not sure if need to abbreviate Certificate to Cert and PrivateKey to Key...
> 
> Otherwise straightforward and LGTM with the general approach. Did not realize that bootstrap did not provide a way to get to the secretstoreclient directly.

Squash the commits and update the issue commits style. 
The method added is just a wrapper to secretClient.GetSecret(), and the test of latter has been covered in go-mod-secrets, which is the reason there is no unit test case for it provided.

**Pull request merged**
