### PR TITLE
fix: Rename SecretPath to SecretName

### PR DESCRIPTION
**Pull request by FelixTing**
fix: #550 

If your build fails due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-bootstrap/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [x] I have opened a PR for the related docs change (if not, why?) 
  https://github.com/edgexfoundry/edgex-docs/pull/1095

### CODE REVIEW

**Comment by cloudxxx8** [comment]
@lenny-intel please see whether we can fix this issue in 3.0

**Comment by lenny-intel** [comment]
> @lenny-intel please see whether we can fix this issue in 3.0

@cloudxxx8 , Dang it. :-( We would have to delay the release for this and IMO it isn't worth it for a minor consistency issue. It will have to wait until 4.0.

**Comment by cloudxxx8** [comment]
@lenny-intel it is a real bug, not a consistency issue, so we can fix it in v3.1.

**Comment by lenny-intel** [comment]
> @lenny-intel it is a real bug, not a consistency issue, so we can fix it in v3.1.

@cloudxxx8 , How is this a real bug, rather than a name consistency issue? 

It is a breaking change to 3.0.0. Should discuss in Planning next week.

**Comment by cloudxxx8** [comment]
@lenny-intel it's my misunderstanding of the error log.  I thought code tried to access `SecretName` anyway.
On the other hand it's the bug in the core-command config.  We are using `SecretName` in core-command.
https://github.com/edgexfoundry/edgex-go/blob/1fb6775d8804dda106fccace673c66bb187c3e57/cmd/core-command/res/configuration.yaml#L31

We have to change the config or merge this PR in v3.1.

**Comment by lenny-intel** [comment]
@FelixTing , since the configuration YAML has the correct name, this is bug fix and not a breaking change as I first thought.
Please update the commit message an PR to remove specifying it as breaking change. THX!

**Review by lenny-intel — COMMENTED** [review]
LGTM once specifying breaking change is removed.

**Review by lenny-intel — APPROVED** [review]
LGTM

**Pull request merged**
